name: align-rudder
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.76
  - clustalw=2.1
  - cudatoolkit
  - h5py=2.10.0
  - hdf5=1.10.4
  - mkl
  - natsort
  - numpy=1.18.1
  - pandas
  - pip
  - protobuf
  - tensorboard
  - python=3.7.7
  - pytorch=1.5.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn
  - tqdm
  - pip:
    - gym==0.17.2
    - ray==0.8.5
    - tabulate
    - tensorboardx
    - scikit-image==0.17.2
    - git+https://github.com/zuoxingdong/mazelab.git@master
    - git+https://github.com/widmi/widis-lstm-tools
